### ISSUE TITLE
主题与信息不能用中文,能修正下吗？谢谢

### ISSUE THREAD

**Issue by ryanlycch** [X-Mars/Zabbix-Alert-WeChat#1]
./wechat.py test1 "测试" "正常"
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

**Comment by X-Mars** [comment]
脚本是支持UTF8中文的

``` bash
cat /etc/sysconfig/i18n
```

运行以上命令，查看系统编码是否为UTF8

**Comment by ryanlycch** [comment]
cat /etc/sysconfig/i18n
LANG="en_US.UTF-8"

**Comment by X-Mars** [comment]
加入以下三行再试试

``` python
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

**Comment by ryanlycch** [comment]
加这3行就可以了，谢谢了。
