### ISSUE TITLE
zabbix4.0 使用脚本报错 Permission denied: 'config.json'

### ISSUE THREAD

**Issue by xfengfeng** [X-Mars/Zabbix-Alert-WeChat#10]
最近新搭建的zabbix server 4.0，使用了最新的wechat.py，记得以前版本是没有生成config.json，现在新版本脚本生成了config.json，报错是没权限，我已经给config.json配了777权限和chown zabbix，依然还是相同的报错，麻烦看看是什么问题？

Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/wechat.py", line 73, in <module>
Status = SendMessage(User,Agentid,Subject,Content)
File "/usr/lib/zabbix/alertscripts/wechat.py", line 35, in SendMessage
Token = GetTokenFromServer(Corpid, Secret)
File "/usr/lib/zabbix/alertscripts/wechat.py", line 24, in GetTokenFromServer
file = open('config.json', 'w')
IOError: [Errno 13] Permission denied: 'config.json'

**Comment by X-Mars** [comment]
这不科学    
手动调用 有问题吗


| |
xtlyk
|
|
xtlyk@126.com
|
签名由网易邮箱大师定制


在2018年10月24日 09:51，Linxf_<notifications@github.com> 写道：

最近新搭建的zabbix server 4.0，使用了最新的wechat.py，记得以前版本是没有生成config.json，现在新版本脚本生成了config.json，报错是没权限，我已经给config.json配了777权限和chown zabbix，依然还是相同的报错，麻烦看看是什么问题？

Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/wechat.py", line 73, in
Status = SendMessage(User,Agentid,Subject,Content)
File "/usr/lib/zabbix/alertscripts/wechat.py", line 35, in SendMessage
Token = GetTokenFromServer(Corpid, Secret)
File "/usr/lib/zabbix/alertscripts/wechat.py", line 24, in GetTokenFromServer
file = open('config.json', 'w')
IOError: [Errno 13] Permission denied: 'config.json'

**Comment by xfengfeng** [comment]
手动调用是OK的，微信上可以接收到消息。

[root@zabbix alertscripts]# python wechat.py 44 44 44 44
{u'access_token': u'oRDRbuoskoa0Z1stm7SNQhA0n7ieILobGEec2H4aBGO3aQATnSSjpmhY6ZaAt1s-Np2Skg3ExzP4J6v-hOj4qZgyY9kWeDiSV57x3U-cogptfmLe3p-b6RCZkifnomcNfRSVGWsy09b9EKnN0cI6IytRKf_gVo1oCPwMs9661T50CWbn8mveGwHhfa_jLGzi5FF9RIbJO1efGg', u'expires_in': 7200, u'errcode': 0, u'errmsg': u'ok'}
{u'invaliduser': u'44', u'errcode': 0, u'errmsg': u'ok'}
{u'invaliduser': u'44', u'errcode': 0, u'errmsg': u'ok'}

**Comment by X-Mars** [comment]
chown zabbix.zabbix wechat.py
chown apache.apache wechat.py
这两个分别试试




| |
xtlyk
|
|
xtlyk@126.com
|
签名由网易邮箱大师定制


在2018年10月24日 11:19，Linxf_<notifications@github.com> 写道：

手动调用是OK的，微信上可以接收到消息。

[root@zabbix alertscripts]# python wechat.py 44 44 44 44
{u'access_token': u'oRDRbuoskoa0Z1stm7SNQhA0n7ieILobGEec2H4aBGO3aQATnSSjpmhY6ZaAt1s-Np2Skg3ExzP4J6v-hOj4qZgyY9kWeDiSV57x3U-cogptfmLe3p-b6RCZkifnomcNfRSVGWsy09b9EKnN0cI6IytRKf_gVo1oCPwMs9661T50CWbn8mveGwHhfa_jLGzi5FF9RIbJO1efGg', u'expires_in': 7200, u'errcode': 0, u'errmsg': u'ok'}
{u'invaliduser': u'44', u'errcode': 0, u'errmsg': u'ok'}
{u'invaliduser': u'44', u'errcode': 0, u'errmsg': u'ok'}

**Comment by X-Mars** [comment]
兄弟  问题解决了吗

**Comment by X-Mars** [comment]
已修复，请更新代码

**Comment by Alpha-liu** [comment]
碰到了同样的问题，单独命令测试正常，zabbix触发就报下面的错误。


>  File "/usr/lib/zabbix/alertscripts/wechat.py", line 73, in <module>
>  Status = SendMessage(User,Agentid,Subject,Content)
>  File "/usr/lib/zabbix/alertscripts/wechat.py", line 53, in SendMessage
>  Token = GetTokenFromServer(Corpid, Secret)
>  File "/usr/lib/zabbix/alertscripts/wechat.py", line 24, in GetTokenFromServer
>  file = open('/tmp/zabbix_wechat_config.json', 'w')
> IOError: [Errno 13] Permission denied: '/tmp/zabbix_wechat_config.json'




主要还是权限问题，先前只加了zabbix权限，后来加了apache的权限上面的报警就正常了。建议把这个放在FAQ里面，这样好找些。
> chown zabbix.zabbix wechat.py
> chown apache.apache wechat.py

**Comment by X-Mars** [comment]
@Alpha-liu  收到  近期会更新 谢谢

**Comment by qlintel** [comment]
Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/wechat.py", line 73, in <module>
Status = SendMessage(User,Agentid,Subject,Content)
File "/usr/lib/zabbix/alertscripts/wechat.py", line 53, in SendMessage
Token = GetTokenFromServer(Corpid, Secret)
File "/usr/lib/zabbix/alertscripts/wechat.py", line 24, in GetTokenFromServer
file = open('/tmp/zabbix_wechat_config.json', 'w')
IOError: [Errno 13] Permission denied: '/tmp/zabbix_wechat_config.json'

按照以下操作增加权限后刚开始正常，但后面又会出现同样报错，麻烦看看什么问题？
chown zabbix.zabbix wechat.py
chown apache.apache wechat.py

centos7 和 zabbix5.0

**Comment by charnet1019** [comment]
应该是权限的问题发自我的华为手机-------- 原始邮件 --------发件人： Ling_Qin <notifications@github.com>日期： 2021年1月4日周一 11:03收件人： X-Mars/Zabbix-Alert-WeChat <Zabbix-Alert-WeChat@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [X-Mars/Zabbix-Alert-WeChat] zabbix4.0 使用脚本报错 Permission denied: 'config.json' (#10)

Traceback (most recent call last):

File "/usr/lib/zabbix/alertscripts/wechat.py", line 73, in 

Status = SendMessage(User,Agentid,Subject,Content)

File "/usr/lib/zabbix/alertscripts/wechat.py", line 53, in SendMessage

Token = GetTokenFromServer(Corpid, Secret)

File "/usr/lib/zabbix/alertscripts/wechat.py", line 24, in GetTokenFromServer

file = open('/tmp/zabbix_wechat_config.json', 'w')

IOError: [Errno 13] Permission denied: '/tmp/zabbix_wechat_config.json'

按照以下操作增加权限后刚开始正常，但后面又会出现同样报错，麻烦看看什么问题？

chown zabbix.zabbix wechat.py

chown apache.apache wechat.py

centos7 和 zabbix5.0

**Comment by qlintel** [comment]
> 应该是权限的问题发自我的华为手机-------- 原始邮件 --------发件人： Ling_Qin <notifications@github.com>日期： 2021年1月4日周一 11:03收件人： X-Mars/Zabbix-Alert-WeChat <Zabbix-Alert-WeChat@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主 题： Re: [X-Mars/Zabbix-Alert-WeChat] zabbix4.0 使用脚本报错 Permission denied: 'config.json' (#10) Traceback (most recent call last): File "/usr/lib/zabbix/alertscripts/wechat.py", line 73, in Status = SendMessage(User,Agentid,Subject,Content) File "/usr/lib/zabbix/alertscripts/wechat.py", line 53, in SendMessage Token = GetTokenFromServer(Corpid, Secret) File "/usr/lib/zabbix/alertscripts/wechat.py", line 24, in GetTokenFromServer file = open('/tmp/zabbix_wechat_config.json', 'w') IOError: [Errno 13] Permission denied: '/tmp/zabbix_wechat_config.json' 按照以下操作增加权限后刚开始正常，但后面又会出现同样报错，麻烦看看什么问题？ chown zabbix.zabbix wechat.py chown apache.apache wechat.py centos7 和 zabbix5.0 —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe

是的，已给/tmp/zabbix_wechat_config.json这个文件赋予apache权限，目前使用正常。谢谢~
