### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by 5sdba** [X-Mars/Zabbix-Alert-WeChat#11]
请问大佬，这个有支持企业微信markdown,卡片形式的告警么

**Comment by X-Mars** [comment]
https://github.com/X-Mars/Zabbix-Alert-WeChat/blob/025eaf6077e450374625cd0ceccdd17e4333b5d7/wechat.py#L43
https://work.weixin.qq.com/api/doc#90000/90135/90236/markdown%E6%B6%88%E6%81%AF
对照改一下就好了，原理都是一样的

**Comment by 5sdba** [comment]
搞定，谢谢大佬。
