### ISSUE TITLE
微信Token调用，一天只能调用20次。如果发生频繁告警。

### ISSUE THREAD

**Issue by UnknowName** [X-Mars/Zabbix-Alert-WeChat#2]
微信Token调用，一天只能调用20次。如果发生频繁告警。Token将很快用完。程序还要优化。

**Comment by X-Mars** [comment]
好好看看开发文档
http://qydev.weixin.qq.com/wiki/index.php?title=%E5%8F%91%E6%B6%88%E6%81%AF
