### ISSUE TITLE
配置过程中遇到的一点小问题

### ISSUE THREAD

**Issue by p1raya** [X-Mars/Zabbix-Alert-WeChat#3]
首先表示感谢，你的脚本非常好用！
配置过程中发现几个小问题，在此提一下。

报警脚本默认存放路径应该是：
> /usr/local/share/zabbix/alertscripts 
或者 **AlertScriptsPath** 指定的其它位置。

需要提供以下三个宏作为脚本参数：
- {ALERT.SENDTO}
- {ALERT.SUBJECT}
- {ALERT.MESSAGE}

加上 "**toparty**" 会始终给整个部门发消息，不需要的话建议注释掉。
如单独给某几人发，还可选择在企业号通讯录给用户打标签，用 "**totag**" 发消息。

代码里有几个空行多加了空格，建议去掉。

**Comment by X-Mars** [comment]
谢谢你提出的建议。我会更新README.md
