### ISSUE TITLE
微信出现重复报警，主要是zabbix的problem重复报警，邮件报警无此问题

### ISSUE THREAD

**Issue by carrison** [X-Mars/Zabbix-Alert-WeChat#4]
无论邮件还是微信，zabbix的告警源应该是唯一的，为什么微信告警经常出现重复的problem告警？

**Comment by X-Mars** [comment]
脚本内只发送一次信息，如果重复发送，请确认触发器状态。

**Comment by carrison** [comment]
不好意思，是我配置的问题，我多配了个action，是多余的，去除就ok了。

**Comment by X-Mars** [comment]
ok  欢迎再来提意见
