### ISSUE TITLE
新版本执行报错

### ISSUE THREAD

**Issue by ChowRex** [X-Mars/Zabbix-Alert-WeChat#6]
使用pip install requests 安装完毕执行 ./wechat.py NAME test 123 （已配置好所有公众号信息），报错如下

ImportError: No module named packages.urllib3

使用第二种源码安装方式 执行报错

ImportError: cannot import name UnrewindableBodyError

解决方案
原网址 https://stackoverflow.com/questions/27440060/how-to-fix-importerror-no-module-named-packages-urllib3
第二个答案
sudo pip install --upgrade requests

然后执行一切正常

**Comment by X-Mars** [comment]
谢谢 已经更新README.md

**Comment by ChowRex** [comment]
您辛苦
