### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by heaquan** [X-Mars/Zabbix-Alert-WeChat#7]
提示这个错误？
usr/lib/zabbix/alertscripts/zabbix-wachat.sh: line 3: import: command not found
/usr/lib/zabbix/alertscripts/zabbix-wachat.sh: line 4: import: command not found
/usr/lib/zabbix/alertscripts/zabbix-wachat.sh: line 7: syntax error near unexpected token `reload'
/usr/lib/zabbix/alertscripts/zabbix-wachat.sh: line 7: `reload(sys)'

**Comment by X-Mars** [comment]
你的python环境有问题，重新编译python再试试吧

**Comment by heaquan** [comment]
需要什么版本的python呢
我重新安装了2.7.9的版本还是有同样的问题

**Comment by X-Mars** [comment]
python2.6 2.7

**Comment by heaquan** [comment]
重新编译安装后还是同样的问题？

**Comment by X-Mars** [comment]
多尝试吧，从报错看是python问题，不是脚本的问题。
